include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true   # Ya la tienes, bien para consistencia
    avoid_print: false           # Permite usar print sin warning, útil en desarrollo
    avoid_dynamic_calls: true    # Evita llamadas dinámicas que pueden causar errores
    always_declare_return_types: true  # Obliga a declarar tipos de retorno para claridad
    prefer_final_locals: true   # Usa final para variables que no cambian
    avoid_empty_else: true       # Evita else vacío innecesario
    prefer_const_constructors: true  # Usa constructores const donde se pueda para eficiencia
    prefer_const_literals_to_create_immutables: true # Literales const donde se pueda
    unnecessary_null_checks: true # Detecta null checks redundantes
    no_duplicate_case_values: true # Evita casos duplicados en switch
    avoid_function_literals_in_foreach_calls: false # Permite funciones inline en foreach para comodidad
    prefer_is_empty: true         # Prefiere .isEmpty en vez de length == 0
    always_use_package_imports: true  # Consistencia en imports
    prefer_typing_uninitialized_variables: true  # Mejora claridad declarando tipos
    lines_longer_than_80_chars: false # Desactiva regla que puede ser molesta
    camel_case_types: true        # Tipos con camelCase
    curly_braces_in_flow_control_structures: true # Usa siempre llaves {}, evita errores

analyzer:
  errors:
    use_build_context_synchronously: ignore
  exclude:
    - '**/*.g.dart' # No analizar código generado (ejemplo: freezed, json_serializable)
    - '**/*.freezed.dart'

