name: tetsugym
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Icons
  material_symbols_icons: ^4.2867.0

  # State
  flutter_riverpod: ^2.6.1

  # General
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  timezone: ^0.10.1
  cached_network_image: ^3.4.1
  path_provider: ^2.1.5
  blur: ^4.0.2
  file_picker: ^10.3.2

  # Animations
  lottie: ^3.3.1
  animate_do: ^4.2.0

  # Localizations
  flutter_localizations:
    sdk: flutter

  # Routes
  go_router: ^16.0.0

  # Firebase
  firebase_core: ^3.15.1
  firebase_messaging: ^15.2.9
  firebase_auth: ^5.6.2
  firebase_remote_config: ^5.4.7
  cloud_firestore: ^5.6.12

  # Modular
  flutter_modular: ^6.4.1

 # Shared preferences
  shared_preferences: ^2.5.3 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/lottie/

    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/to/resolution-aware-images

    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/to/asset-from-package

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
  fonts:
    - family: FunnelDisplayRegular
      fonts:
        - asset: assets/fonts/FunnelDisplay/FunnelDisplay-Regular.ttf

    - family: FunnelDisplayLight
      fonts:
        - asset: assets/fonts/FunnelDisplay/FunnelDisplay-Light.ttf

    - family: FunnelDisplayMedium
      fonts:
        - asset: assets/fonts/FunnelDisplay/FunnelDisplay-Medium.ttf

    - family: FunnelDisplaySemiBold
      fonts:
        - asset: assets/fonts/FunnelDisplay/FunnelDisplay-SemiBold.ttf

    - family: FunnelDisplayBold
      fonts:
        - asset: assets/fonts/FunnelDisplay/FunnelDisplay-Bold.ttf

    - family: FunnelDisplayExtraBold
      fonts:
        - asset: assets/fonts/FunnelDisplay/FunnelDisplay-ExtraBold.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
