name: tetsugym
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # State
  flutter_riverpod: ^2.6.1

  # General
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  timezone: ^0.10.1
  cached_network_image: ^3.4.1
  path_provider: ^2.1.5
  blur: ^4.0.2

  # Animations
  lottie: ^3.3.1
  animate_do: ^4.2.0

  # Localizations
  flutter_localizations:
    sdk: flutter

  # Routes
  go_router: ^16.0.0

  # Firebase
  firebase_core: ^3.15.1
  firebase_messaging: ^15.2.9
  firebase_auth: ^5.6.2
  firebase_remote_config: ^5.4.7

  # Modular
  flutter_modular: ^6.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/lottie/

    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/to/resolution-aware-images

    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/to/asset-from-package

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
  fonts:
    - family: MontserratRegular
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf

    - family: MontserratItalic
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Italic.ttf

    - family: MontserratBold
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf

    - family: MontserratBoldItalic
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-BoldItalic.ttf

    - family: MontserratSemiBold
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf

    - family: MontserratSemiBoldItalic
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-SemiBoldItalic.ttf

    - family: MontserratExtraBold
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBold.ttf

    - family: MontserratExtraBoldItalic
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBoldItalic.ttf

    - family: MontserratBlack
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Black.ttf

    - family: MontserratBlackItalic
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-BlackItalic.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
