// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWhs-q8-3mZ2LSKRBS92LVhO2s74bhsio',
    appId: '1:29797062020:web:e8a3aefdf35803a647b9d1',
    messagingSenderId: '29797062020',
    projectId: 'tetsugym',
    authDomain: 'tetsugym.firebaseapp.com',
    storageBucket: 'tetsugym.firebasestorage.app',
    measurementId: 'G-G69J9SWSS3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF3pmtx1fW8Ia_Wl9VwKu6tb77yJJTuVQ',
    appId: '1:29797062020:android:005f699ec9455c5647b9d1',
    messagingSenderId: '29797062020',
    projectId: 'tetsugym',
    storageBucket: 'tetsugym.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3ypD24Jdy7A1PB2sPCruIHt9CWmesE_I',
    appId: '1:29797062020:ios:b7a49bdc734c669847b9d1',
    messagingSenderId: '29797062020',
    projectId: 'tetsugym',
    storageBucket: 'tetsugym.firebasestorage.app',
    iosClientId: '29797062020-dlkgq3201i044odllp1nj3582fb44b4v.apps.googleusercontent.com',
    iosBundleId: 'com.luisadrianpineda.tetsugym',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3ypD24Jdy7A1PB2sPCruIHt9CWmesE_I',
    appId: '1:29797062020:ios:b7a49bdc734c669847b9d1',
    messagingSenderId: '29797062020',
    projectId: 'tetsugym',
    storageBucket: 'tetsugym.firebasestorage.app',
    iosClientId: '29797062020-dlkgq3201i044odllp1nj3582fb44b4v.apps.googleusercontent.com',
    iosBundleId: 'com.luisadrianpineda.tetsugym',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWhs-q8-3mZ2LSKRBS92LVhO2s74bhsio',
    appId: '1:29797062020:web:60c39bb1ea9b5f0c47b9d1',
    messagingSenderId: '29797062020',
    projectId: 'tetsugym',
    authDomain: 'tetsugym.firebaseapp.com',
    storageBucket: 'tetsugym.firebasestorage.app',
    measurementId: 'G-96EZB8NM5T',
  );
}
